export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const ADD_GROWROOM = 'ADD_GROWROOM';
export const GROWROOM_ERROR = 'GROWROOM_ERROR';
export const FETCH_GROWROOMS = 'FETCH_GROWROOMS';
export const FETCH_RECENT = 'FETCH_RECENT';
